# Generated by Django 4.2 on 2026-04-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_rol_presupuesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
