# Generated by Django 4.2 on 2026-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contrato', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('Ingeniero Civil', 'Ingeniero Civil'), ('Arquitecta', 'Arquitecta'), ('Maestro Albañil', 'Maestro Albañil'), ('Ayudante General', 'Ayudante General'), ('Electricista', 'Electricista'), ('Plomera', 'Plomera'), ('Pintor', 'Pintor'), ('Supervisora de Obra', 'Supervisora de Obra')], max_length=100)),
            ],
        ),
    ]
